---
- name: create postgresql container
  docker_container:
    name: "postgres_container"
    image: postgres
    state: started
    restart_policy: always
    env:
       POSTGRES_PASSWORD: "{{ postgrespassword }}"
    volumes:
        /opt/postgres/data:/var/lib/postgresql/data

- name: create user
  shell: docker exec  postgres_container psql -U postgres --command "CREATE USER django WITH SUPERUSER PASSWORD '{{ djangopostgrespassword }}';"

- name: create database
  shell: docker exec  postgres_container psql -U postgres --command "CREATE DATABASE django;"

- name: create database
  shell: docker exec  postgres_container psql -U postgres --command "GRANT ALL privileges ON DATABASE django TO django;"