---
- name: create postgres directory
  file: state=directory path="/opt/postgres/data"

- name: create postgresql container
  docker_container:
    name: "postgres_container"
    image: postgres
    state: started
    restart_policy: always
    env:
       POSTGRES_PASSWORD: "{{ postgrespassword }}"
    volumes:
        /opt/postgres/data:/var/lib/postgresql/data
  notify:
      - create user
      - create database
      - create database